using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Web.UI;



[assembly: AssemblyTitle("TimeNAction")]
[assembly: AssemblyDescription("Data Aquarium Framework application library")]
[assembly: AssemblyCompany("TimeNAction")]
[assembly: AssemblyProduct("TimeNAction Aquarium in the Box")]
[assembly: AssemblyCopyright("Copyright © TimeNAction 2012")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: WebResource("TimeNAction.Scripts._System.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.Web.DataView.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.Web.DataViewResources.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.Web.DataViewResources.en_US.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.Web.Menu.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.MicrosoftAjax.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.MicrosoftAjaxWebForms.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.MicrosoftAjaxApplicationServices.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Scripts.AjaxControlToolkit.js", "text/javascript")]
[assembly: WebResource("TimeNAction.Theme.Plastic.css", "text/css", PerformSubstitution=true)]
[assembly: WebResource("TimeNAction.Theme.Acrobat.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ActionBarBg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ActionBarDiv.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ActionGroupBg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.AddBookmark.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.AdvancedSearch.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.arrow-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.arrow-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ArrowBkg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Attach.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Attention.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.BACK.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Bullet.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Calendar.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.CheckMark.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.CheckMark2.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.CheckMarkLarge.GIF", "image/GIF")]
[assembly: WebResource("TimeNAction.Theme.Close.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.DataSheet.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Delete.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.DropArrow.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Edit.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.EditMode.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Erase.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Excel.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.EXCLAIM.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ExportCsv.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ExportRowset.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ExportRss.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Filter.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.FilterOff.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.FilterOffDisabled.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.FORWARD.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.HeaderBg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.HeaderBgActive.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.html-editor-buttons.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.ICONGO.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Import.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.Import2.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.Information.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Maximize.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.MenuBg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.MenuBgLarge.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Minimize.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.MultiPage.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Navigate.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.NavShape.jpg", "image/jpg")]
[assembly: WebResource("TimeNAction.Theme.NavStrip.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.New.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.NewLarge.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ObjectRef.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.PageContentRightSide.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.PageHeader.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ParaHeaderBkg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Paste.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.PopupArrow.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Print.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.QuickFind.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Refresh.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.Save.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SaveLarge.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Search.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Search.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.SearchPlusMinus.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.SettingsGraphic.jpg", "image/jpg")]
[assembly: WebResource("TimeNAction.Theme.SiteActionsActiveTab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SiteActionsInactiveTab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SortAZ.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SortDown.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SortUp.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.SortZA.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.StatusBar.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-animated-overlay.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_flat_0_aaaaaa_40x100.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_flat_75_ffffff_40x100.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_glass_55_fbf9ee_1x400.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_glass_65_ffffff_1x400.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_glass_75_dadada_1x400.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_glass_75_e6e6e6_1x400.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_glass_95_fef1ec_1x400.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-bg_highlight-soft_75_cccccc_1x100.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-icons_222222_256x240.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-icons_2e83ff_256x240.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-icons_454545_256x240.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-icons_888888_256x240.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.syst-ui-icons_cd0a0a_256x240.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.tab-active-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-left-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-right-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-active.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-active-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-active-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-active.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-hover-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-hover-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-hover.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-bottom.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-left-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-right-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-hover.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-left-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-left-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-left.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-line.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-right-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-right-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-right.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-verticalleft.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab-verticalright.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.tab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TabsActiveTab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TabsBar.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TabsInactiveTab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TabsSelectedTab.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TaskBoxBkg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TaskBullet.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.TopShape.jpg", "image/jpg")]
[assembly: WebResource("TimeNAction.Theme.TreeControls.png", "image/png")]
[assembly: WebResource("TimeNAction.Theme.Undo.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.ViewNameBg.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Wait.gif", "image/gif")]
[assembly: WebResource("TimeNAction.Theme.Word.gif", "image/gif")]
